spring:
  redis:
        host: 192.168.1.158
#        password:
        port: 6381
        pool:
            max-wait: -1
            max-idle: 20
            min-idle: 20
        timeout: 0
#        database: 0
